language: node_js
node_js:
  - '8'
cache:
  bundler: true
  directories:
    - /home/travis/.rvm/
    - node_modules # NPM packages
before_install:
  - 'sudo apt-get install unzip'
  - scripts/install/sonar-scanner
  - scripts/install/ruby
  - scripts/install/changelog-generator
  - scripts/install/chandler
after_success: 
  - 'npm run coveralls'
  - 'npm run sonar'
  - 'npm run changelog'
  - 'npm run github-release'